places = ['Peking', 'New York', 'Paris', 'London','Vienna']
print(places)
print(sorted(places))
print(places)
print(sorted(places,reverse=True))
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse=True)
print(places)
print("The length of the list: " + str(len(places)))